// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/slotmachine/backend/domain/admin"
	"github.com/slotmachine/backend/domain/player"
	"github.com/slotmachine/backend/internal/api/handler"
	"github.com/slotmachine/backend/internal/api/middleware"
	"github.com/slotmachine/backend/internal/config"
	"github.com/slotmachine/backend/internal/db"
	"github.com/slotmachine/backend/internal/game/engine"
	"github.com/slotmachine/backend/internal/infra/repository"
	"github.com/slotmachine/backend/internal/infra/storage"
	"github.com/slotmachine/backend/internal/pkg/cache"
	"github.com/slotmachine/backend/internal/pkg/logger"
	"github.com/slotmachine/backend/internal/server"
	"github.com/slotmachine/backend/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApplication creates a fully initialized application using Wire
func InitializeApplication() (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger := logger.ProvideLogger(configConfig)
	gormDB, err := db.ProvideDatabase(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	cacheCache := cache.ProvideCache(configConfig, loggerLogger)
	app := server.ProvideFiberApp(configConfig, loggerLogger)
	rateLimiter := middleware.ProvideRateLimiter(configConfig, loggerLogger)
	redisClient := cache.ProvideRedisClient(configConfig, loggerLogger)
	trialRateLimiter := middleware.ProvideTrialRateLimiter(configConfig, redisClient, loggerLogger)
	playerRepository := repository.NewPlayerGormRepository(gormDB)
	gameRepository := repository.NewGameGormRepository(gormDB)
	playerSessionRepository := repository.NewPlayerSessionGormRepository(gormDB)
	playerService := service.NewPlayerService(playerRepository, gameRepository, playerSessionRepository, redisClient, configConfig, loggerLogger)
	authHandler := handler.NewAuthHandler(playerService, loggerLogger)
	playerHandler := handler.NewPlayerHandler(playerService, loggerLogger)
	sessionRepository := repository.NewSessionGormRepository(gormDB)
	sessionService := service.NewSessionService(sessionRepository, playerRepository, loggerLogger)
	sessionHandler := handler.NewSessionHandler(sessionService, loggerLogger)
	spinRepository := repository.NewSpinGormRepository(gormDB)
	reelstripRepository := repository.NewReelStripGormRepository(gormDB, cacheCache)
	reelstripService := service.NewReelStripService(reelstripRepository, loggerLogger)
	gameEngine := engine.ProvideGameEngine(cacheCache, reelstripService)
	freespinsRepository := repository.NewFreeSpinsGormRepository(gormDB)
	txManager := repository.NewTxManager(gormDB)
	provablyFairGormRepository := repository.NewProvablyFairGormRepository(gormDB)
	pfSessionCache := cache.ProvidePFSessionCache(redisClient, loggerLogger)
	provablyFairService, err := service.ProvideProvablyFairService(provablyFairGormRepository, pfSessionCache, reelstripRepository, configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	spinService := service.ProvideSpinService(spinRepository, playerRepository, sessionRepository, gameEngine, freespinsRepository, reelstripRepository, txManager, provablyFairService, loggerLogger)
	spinHandler := handler.NewSpinHandler(spinService, loggerLogger)
	freeSpinsService := service.ProvideFreeSpinsService(sessionRepository, freespinsRepository, spinRepository, playerRepository, gameEngine, provablyFairService, loggerLogger)
	freeSpinsHandler := handler.NewFreeSpinsHandler(freeSpinsService, loggerLogger)
	provablyFairHandler := handler.NewProvablyFairHandler(provablyFairService, loggerLogger)
	adminReelStripHandler := handler.NewAdminReelStripHandler(reelstripService, loggerLogger, cacheCache)
	adminPlayerAssignmentHandler := handler.NewAdminPlayerAssignmentHandler(reelstripService, loggerLogger, cacheCache)
	adminRepository := repository.NewAdminGormRepository(gormDB)
	adminService := service.NewAdminService(adminRepository, playerRepository, reelstripRepository, gameRepository, playerSessionRepository, redisClient, configConfig, loggerLogger)
	adminAuthHandler := handler.NewAdminAuthHandler(adminService, loggerLogger)
	adminManagementHandler := handler.NewAdminManagementHandler(adminService, loggerLogger)
	adminPlayerHandler := handler.NewAdminPlayerHandler(adminService, loggerLogger)
	gameHandler := handler.NewGameHandler(gameRepository, loggerLogger)
	storageStorage, err := storage.ProvideStorage(configConfig)
	if err != nil {
		return nil, err
	}
	adminGameHandler := handler.NewAdminGameHandler(gameRepository, storageStorage, loggerLogger)
	adminUploadHandler := handler.NewAdminUploadHandler(storageStorage, loggerLogger)
	adminChunkedUploadHandler := handler.NewAdminChunkedUploadHandler(storageStorage, loggerLogger, redisClient)
	adminDirectUploadHandler := handler.NewAdminDirectUploadHandler(storageStorage, loggerLogger)
	trialService := service.ProvideTrialService(redisClient, loggerLogger)
	trialHandler := handler.NewTrialHandler(trialService, trialRateLimiter, loggerLogger)
	trialSpinHandler := handler.NewTrialSpinHandler(spinService, loggerLogger)
	trialFreeSpinsHandler := handler.NewTrialFreeSpinsHandler(trialService, gameEngine, loggerLogger)
	trialSessionHandler := handler.NewTrialSessionHandler(loggerLogger)
	trialPlayerHandler := handler.NewTrialPlayerHandler(loggerLogger)
	application := &Application{
		Config:                       configConfig,
		Logger:                       loggerLogger,
		DB:                           gormDB,
		Cache:                        cacheCache,
		App:                          app,
		RateLimiter:                  rateLimiter,
		TrialRateLimiter:             trialRateLimiter,
		AuthHandler:                  authHandler,
		PlayerHandler:                playerHandler,
		SessionHandler:               sessionHandler,
		SpinHandler:                  spinHandler,
		FreeSpinsHandler:             freeSpinsHandler,
		ProvablyFairHandler:          provablyFairHandler,
		ProvablyFairService:          provablyFairService,
		SpinService:                  spinService,
		FreeSpinsService:             freeSpinsService,
		AdminReelStripHandler:        adminReelStripHandler,
		AdminPlayerAssignmentHandler: adminPlayerAssignmentHandler,
		AdminAuthHandler:             adminAuthHandler,
		AdminManagementHandler:       adminManagementHandler,
		AdminPlayerHandler:           adminPlayerHandler,
		GameHandler:                  gameHandler,
		AdminGameHandler:             adminGameHandler,
		AdminUploadHandler:           adminUploadHandler,
		AdminChunkedUploadHandler:    adminChunkedUploadHandler,
		AdminDirectUploadHandler:     adminDirectUploadHandler,
		TrialHandler:                 trialHandler,
		TrialSpinHandler:             trialSpinHandler,
		TrialFreeSpinsHandler:        trialFreeSpinsHandler,
		TrialSessionHandler:          trialSessionHandler,
		TrialPlayerHandler:           trialPlayerHandler,
		AdminService:                 adminService,
		PlayerService:                playerService,
		TrialService:                 trialService,
		Storage:                      storageStorage,
	}
	return application, nil
}

// wire.go:

// Application holds all application dependencies
type Application struct {
	Config                       *config.Config
	Logger                       *logger.Logger
	DB                           *gorm.DB
	Cache                        *cache.Cache
	App                          *fiber.App
	RateLimiter                  *middleware.RateLimiter
	TrialRateLimiter             *middleware.TrialRateLimiter // Security: DoS protection for trial mode
	AuthHandler                  *handler.AuthHandler
	PlayerHandler                *handler.PlayerHandler
	SessionHandler               *handler.SessionHandler
	SpinHandler                  *handler.SpinHandler
	FreeSpinsHandler             *handler.FreeSpinsHandler
	ProvablyFairHandler          *handler.ProvablyFairHandler
	ProvablyFairService          *service.ProvablyFairService
	SpinService                  *service.SpinService      // For PF injection
	FreeSpinsService             *service.FreeSpinsService // For PF injection
	AdminReelStripHandler        *handler.AdminReelStripHandler
	AdminPlayerAssignmentHandler *handler.AdminPlayerAssignmentHandler
	AdminAuthHandler             *handler.AdminAuthHandler
	AdminManagementHandler       *handler.AdminManagementHandler
	AdminPlayerHandler           *handler.AdminPlayerHandler
	GameHandler                  *handler.GameHandler
	AdminGameHandler             *handler.AdminGameHandler
	AdminUploadHandler           *handler.AdminUploadHandler
	AdminChunkedUploadHandler    *handler.AdminChunkedUploadHandler
	AdminDirectUploadHandler     *handler.AdminDirectUploadHandler
	TrialHandler                 *handler.TrialHandler
	// Trial-specific handlers (separate from production)
	TrialSpinHandler      *handler.TrialSpinHandler
	TrialFreeSpinsHandler *handler.TrialFreeSpinsHandler
	TrialSessionHandler   *handler.TrialSessionHandler
	TrialPlayerHandler    *handler.TrialPlayerHandler
	AdminService          admin.Service
	PlayerService         player.Service
	TrialService          *service.TrialService
	Storage               storage.Storage
}

// Shutdown gracefully shuts down all application resources
func (a *Application) Shutdown() error {
	a.Logger.Info().Msg("Starting graceful shutdown...")

	if err := a.App.Shutdown(); err != nil {
		a.Logger.Error().Err(err).Msg("Failed to shutdown Fiber server")
	} else {
		a.Logger.Info().Msg("Fiber server shutdown complete")
	}

	if a.Cache != nil {
		a.Cache.Close()
		a.Logger.Info().Msg("Cache closed")
	}

	if a.DB != nil {
		if err := db.Close(a.DB, a.Logger); err != nil {
			a.Logger.Error().Err(err).Msg("Failed to close database")
			return err
		}
	}

	a.Logger.Info().Msg("Graceful shutdown complete")
	return nil
}
