-- Create provably fair sessions table
-- One PF session = one server_seed = N spins linked by hash chain
-- Client seed is provided per-spin (not per-session) to ensure server cannot predict outcomes
CREATE TABLE IF NOT EXISTS pf_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    game_session_id UUID NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,

    -- Cryptographic commitment (public from session start)
    server_seed_hash VARCHAR(64) NOT NULL,  -- SHA256(server_seed) - commitment shown to player

    -- Encrypted server seed for recovery (AES-256-GCM encrypted)
    -- This allows recovery if Redis is lost, decrypted only when session ends
    encrypted_server_seed TEXT NOT NULL,

    -- Nonce tracking
    nonce_start BIGINT NOT NULL DEFAULT 1,
    last_nonce BIGINT NOT NULL DEFAULT 0,
    last_spin_hash VARCHAR(64),

    -- Session status
    status VARCHAR(20) NOT NULL DEFAULT 'active',

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE
);

-- Indexes for pf_sessions
CREATE INDEX idx_pf_sessions_player_id ON pf_sessions(player_id);
CREATE INDEX idx_pf_sessions_game_session_id ON pf_sessions(game_session_id);
CREATE INDEX idx_pf_sessions_status ON pf_sessions(status);
CREATE UNIQUE INDEX idx_pf_sessions_active_game_session
    ON pf_sessions(game_session_id)
    WHERE status = 'active';

COMMENT ON TABLE pf_sessions IS 'Provably fair gaming sessions with cryptographic commitments';
COMMENT ON COLUMN pf_sessions.server_seed_hash IS 'SHA256 hash of server seed - public from start, seed revealed after session';
COMMENT ON COLUMN pf_sessions.encrypted_server_seed IS 'AES-256-GCM encrypted server seed for recovery if Redis is lost';

-- Create spin_logs table (APPEND-ONLY audit log)
-- CRITICAL: NO UPDATE, NO DELETE operations allowed on this table
-- Client seed is provided per-spin to ensure server cannot predict outcomes
CREATE TABLE IF NOT EXISTS spin_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pf_session_id UUID NOT NULL REFERENCES pf_sessions(id) ON DELETE RESTRICT,
    spin_id UUID NOT NULL REFERENCES spins(id) ON DELETE RESTRICT,

    -- Sequential tracking
    spin_index BIGINT NOT NULL,
    nonce BIGINT NOT NULL,

    -- Client seed for this spin (provided by client before spin execution)
    -- This ensures server cannot predict outcomes since client contributes randomness
    client_seed VARCHAR(64) NOT NULL,

    -- Hash chain
    spin_hash VARCHAR(64) NOT NULL,       -- SHA256(prev_spin_hash + server_seed + client_seed + nonce)
    prev_spin_hash VARCHAR(64) NOT NULL,  -- Previous spin's hash (server_seed_hash for first spin)

    -- Reel positions for verification (array of 5 integers, one per reel)
    -- These are the random positions generated by the hash-based RNG
    reel_positions JSONB NOT NULL,

    -- Game configuration for this spin (needed to verify with correct reel strips)
    reel_strip_config_id UUID REFERENCES reel_strip_configs(id) ON DELETE RESTRICT,
    game_mode VARCHAR(32),                -- null for normal spin, or: bonus_spin_trigger, etc.
    is_free_spin BOOLEAN NOT NULL DEFAULT false,

    -- Timestamp
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for spin_logs
CREATE INDEX idx_spin_logs_pf_session_id ON spin_logs(pf_session_id);
CREATE INDEX idx_spin_logs_spin_id ON spin_logs(spin_id);
CREATE INDEX idx_spin_logs_created_at ON spin_logs(created_at);
CREATE INDEX idx_spin_logs_reel_strip_config ON spin_logs(reel_strip_config_id);
CREATE UNIQUE INDEX idx_spin_logs_session_index ON spin_logs(pf_session_id, spin_index);
CREATE UNIQUE INDEX idx_spin_logs_session_nonce ON spin_logs(pf_session_id, nonce);

-- Prevent UPDATE/DELETE on spin_logs (append-only)
CREATE OR REPLACE FUNCTION prevent_spin_log_modification()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'spin_logs table is append-only: UPDATE and DELETE are not allowed';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_prevent_spin_log_update
    BEFORE UPDATE ON spin_logs
    FOR EACH ROW
    EXECUTE FUNCTION prevent_spin_log_modification();

CREATE TRIGGER trigger_prevent_spin_log_delete
    BEFORE DELETE ON spin_logs
    FOR EACH ROW
    EXECUTE FUNCTION prevent_spin_log_modification();

COMMENT ON TABLE spin_logs IS 'Append-only audit log for provably fair spins - NO UPDATE/DELETE';
COMMENT ON COLUMN spin_logs.client_seed IS 'Client-provided seed for this spin - ensures server cannot predict outcome';
COMMENT ON COLUMN spin_logs.spin_hash IS 'SHA256(prev_spin_hash + server_seed + client_seed + nonce) - deterministic RNG seed';
COMMENT ON COLUMN spin_logs.prev_spin_hash IS 'Previous spin hash or server_seed_hash for first spin';
COMMENT ON COLUMN spin_logs.reel_positions IS 'Array of 5 reel positions generated by hash-based RNG for verification';
COMMENT ON COLUMN spin_logs.reel_strip_config_id IS 'Reference to reel strip config used - needed for verification';

-- Create session_audits table (stores revealed server_seed after session ends)
CREATE TABLE IF NOT EXISTS session_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pf_session_id UUID NOT NULL UNIQUE REFERENCES pf_sessions(id) ON DELETE RESTRICT,

    -- Revealed data
    server_seed_plaintext VARCHAR(64) NOT NULL,  -- Revealed after session ends
    server_seed_hash VARCHAR(64) NOT NULL,       -- Must match pf_sessions.server_seed_hash
    total_spins BIGINT NOT NULL,

    -- Timestamp
    revealed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for session_audits
CREATE INDEX idx_session_audits_pf_session_id ON session_audits(pf_session_id);
CREATE INDEX idx_session_audits_revealed_at ON session_audits(revealed_at);

-- Prevent modification of session_audits (immutable after creation)
CREATE TRIGGER trigger_prevent_session_audit_update
    BEFORE UPDATE ON session_audits
    FOR EACH ROW
    EXECUTE FUNCTION prevent_spin_log_modification();

CREATE TRIGGER trigger_prevent_session_audit_delete
    BEFORE DELETE ON session_audits
    FOR EACH ROW
    EXECUTE FUNCTION prevent_spin_log_modification();

COMMENT ON TABLE session_audits IS 'Stores revealed server seeds for client verification - immutable after creation';
COMMENT ON COLUMN session_audits.server_seed_plaintext IS 'Server seed revealed after session ends for client verification';
