// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/slotmachine/backend/domain/reelstrip"
	"github.com/slotmachine/backend/internal/config"
	"github.com/slotmachine/backend/internal/db"
	"github.com/slotmachine/backend/internal/infra/repository"
	"github.com/slotmachine/backend/internal/pkg/cache"
	"github.com/slotmachine/backend/internal/pkg/logger"
	"github.com/slotmachine/backend/internal/service"
)

// Injectors from wire.go:

// InitializeSeedApplication creates a fully initialized seed application using Wire
func InitializeSeedApplication() (*SeedApplication, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger := logger.ProvideLogger(configConfig)
	gormDB, err := db.ProvideDatabase(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	cacheCache := cache.ProvideCache(configConfig, loggerLogger)
	reelstripRepository := repository.NewReelStripGormRepository(gormDB, cacheCache)
	reelstripService := service.NewReelStripService(reelstripRepository, loggerLogger)
	seedApplication := &SeedApplication{
		Config:              configConfig,
		Logger:              loggerLogger,
		ReelStripService:    reelstripService,
		ReelStripRepository: reelstripRepository,
	}
	return seedApplication, nil
}

// wire.go:

// SeedApplication holds dependencies for the seed script
type SeedApplication struct {
	Config              *config.Config
	Logger              *logger.Logger
	ReelStripService    reelstrip.Service
	ReelStripRepository reelstrip.Repository
}
